local: &local
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *local
  database: db/development.sqlite3

test:
  <<: *local
  database: db/test.sqlite3

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: 5
  database: growantlers_production
  username: growantlers
  password: <%= ENV['GROWANTLERS_DATABASE_PASSWORD'] %>
